### ISSUE TITLE
Apply this patch is failing due to new change in core

### ISSUE THREAD

**Issue by OscarQueralto** [NaN-tic/trytond-patches#10]
The patch is trying to apply changes already done in core.
https://github.com/NaN-tic/trytond-patches/blob/3a9dd755b7f911f1ba5bec0412ffff5304c9cdb7/statement_of_account_2.diff#L23
https://github.com/NaN-tic/trytond-patches/blob/3a9dd755b7f911f1ba5bec0412ffff5304c9cdb7/statement_of_account_2.diff#L24

Core commit with new changes:
https://hg.tryton.org/modules/account/rev/2dd2cdc9f5db

**Comment by jared-nan** [comment]
The patch has been removed as core commit solves de issue.
https://github.com/NaN-tic/trytond-patches/commit/3458475c7d5713cb02080c41d9ee3eebc6486476
